# NOTE: This will run the plotting scripts created for the SCREAM-STRAT project
# It will have to be adjusted for individual purposes.

HS_DIR=/projects/scream_strat/jltorch/held_suarez
TAG=r400-nlev30

#-------------------------------------------------------------------------------
#STAGE_NAME="HELD-SUAREZ CLIMATOLOGY VISUALIZATION"
#echo "Beginning ${STAGE_NAME}..."
#
#python plot_hs94_climatologies.py \
#    --spinup-days 365 \
#    --homme-output ${HS_DIR}/${TAG}-held_suarez.nc \
#    --plot-vars u,T,T_eddy,pnh \
#    --tag ${TAG} \
#    --recalculate true
#
#echo "${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------

PK_DIR=/projects/scream_strat/jltorch/polvani_kushner
TAG=r400-nlev30

#-------------------------------------------------------------------------------
STAGE_NAME="POLVANI-KUSHNER CLIMATOLOGY VISUALIZATION"
echo "Beginning ${STAGE_NAME}..."

python plot_pk02_climatologies.py \
    --spinup-days 1000 \
    --homme-output ${PK_DIR}/${TAG}-held_suarez.nc \
    --plot-vars u,T \
    --tag ${TAG} \
    --working-dir .polvani_kushner/${TAG} \
    --plotting-dir polvani_kushner/${TAG} \
    --recalculate true

echo "${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------